### ISSUE TITLE
What does the 'access' setting do?

### ISSUE THREAD

**Issue by ngm** [spinen/laravel-discourse-sso#10]
> // Check to see if the user has forum access & should be logged in via SSO
>            'access' => null,

Could you give a brief explanation of what this setting does?

We currently have it set to `null`, but SSO from Discourse is working.  

Is it to control from our Laravel site whether we want users on an individual basis to have access to Discourse?

**Comment by ssfinney** [comment]
That is correct. I believe you can set an attribute on your User model to check if this user should be able to access Discourse. Set the name of the attribute here. If 'access' is null, it ignores this check.

This setting will read the attribute's return value of true/false to determine whether this user should access the forum. If not, it returns a 403.

**Comment by jimmypuckett** [comment]
@ssfinney Is there an action item in here or should this be closed?
