### ISSUE TITLE
Middleware

### ISSUE THREAD

**Issue by bbashy** [spinen/laravel-discourse-sso#12]
Would be good if custom middleware was available for the sso route.

Although I mostly only want to check they're activated so using;
```
'access' => 'hasVerifiedEmail', // using Laravel's MustVerifyEmail contract.
```
Will work?

**Comment by ssfinney** [comment]
Hi @bbashy! Interesting idea. Can you try this and see if it'll work? I want to see if the `services.php` will allow the `auth()` helper to be called.

Not sure if it'll work (since Laravel might not be booted at that point), but I think it's worth a shot.

```php
'access' => auth()->user()->hasVerifiedEmail(),
```

**Comment by jimmypuckett** [comment]
@ssfinney, we could just put the middleware array in the config, so that on [line 22 of SsoServiceProvider.php](
https://github.com/spinen/laravel-discourse-sso/blob/df5e3446f0bcf8bb5e214510e8bfd75c2198c3eb/src/SsoServiceProvider.php#L22) could be...

```php
$this->app['router']->group(["middleware" => $this->app['config']->get('services.discourse.middleware')], function (Router $router) {
```

instead of...

```php
$this->app['router']->group(["middleware" => ["web", "auth"]], function (Router $router) {
```

**Comment by jimmypuckett** [comment]
Actually, should be..

```php
$this->app['router']->group(["middleware" => $this->app['config']->get('services.discourse.middleware', ["web", "auth"])], function (Router $router) {
```

to be backwards compatible.

**Comment by ssfinney** [comment]
Oh, I see. So we could just let the middlewares get passed in through a new config.

Either way is fine. I can knock out that new issue.

**Comment by jimmypuckett** [comment]
@bbashy Would you be good with this solution?  Would it meet your needs?

**Comment by bbashy** [comment]
Yeah a new config array item to set the middleware for the route is perfect.

For now I’ve made an accessor on the User model so it is working but a middleware that’s already available in Laravel would be helpful to most using the package.

Thanks :)

**Comment by jimmypuckett** [comment]
@bbashy It has been nuts at the office & since you had a work around, we put this off for a bit.  Anyhow, I have made PR #13 that I assigned to @ssfinney, so once he reviews/merges it, then we will tag a new version.

**Comment by jimmypuckett** [comment]
I just pushed tag 2.1.0, so that will allow configuring the middleware.
