### ISSUE TITLE
Issue if not already logged into laravel

### ISSUE THREAD

**Issue by robthompsonweb** [spinen/laravel-discourse-sso#18]
So if I am already logged into laravel this works great and connects me.

However if I click through from discourse and I am not logged, I just get a 500 error.

Havent had chance to dig into it, but expected behaviour would be to redirect me to login page and then back here on successful login (unless I am missing something).

![image](https://user-images.githubusercontent.com/5874650/65151061-3fc08880-da1d-11e9-8bce-c62740818d70.png)

**Comment by jimmypuckett** [comment]
This is an interesting flow that we need to dig into & see what is going on.  To repeat what I am understanding you report... if you are not logged into your Laravel site & then go to your Discourse site, you get the attached 500 error, but the "expected" behavior would be to get to the login screen.

I don't think that we have ever tried that.  For our use case, the clients are always logged into our site & then get the link to the discourse site.

**Comment by cocochepeau** [comment]
That'd be nice to have IMO.

* sign in on Discourse
* redirect to SSO url
* check whether or not the user is logged in (laravel)
* [1] redirect to laravel login screen if that's not the case, then redirect back to SSO url on successful login; [2] otherwise SSO can redirect back to Discourse as "normal" behavior

**Comment by ssfinney** [comment]
We've got a similar use case to work using this package. Here's what we did:

- In Discourse, we've set it to allow SSO login, but disable anonymous users, and redirect to Laravel when not authenticated. So when I hit Discourse directly, I'm redirected to Laravel. And on logout, I get redirected to Laravel also.
- Upon redirect, I authenticate with Laravel and am redirected to the SSO URL
- The SSO is done, and I'm authenticated into Discourse (provided that my Laravel permissions allow it)

I'm happy to share our Discourse settings if that's helpful! Let us know if this makes sense, or if there's still another use case that we don't cover.

**Comment by cocochepeau** [comment]
It'd be super helpful to see your Discourse settings, yes!

**Comment by ssfinney** [comment]
OK, here our Discourse settings under Admin -> Login. The red boxes are hiding our Laravel URL. Let me know what you think after reviewing these and trying them out.

[Discourse settings](https://www.dropbox.com/s/1cfe9dzq9b6ez74/Discourse%20settings.png?dl=0)

EDIT: You might need to download that file to view it properly.

**Comment by jimmypuckett** [comment]
@cocochepeau Did you find a difference in the configs that we can document?  I am going to close this as it is working for us, but if we can identify a problem or what to document, then we can reopen.

thanks.

**Comment by robthompsonweb** [comment]
If anyone is still trying to get this to work, a simple forked solution here:
https://github.com/robthompsonweb/laravel-discourse-sso/commit/a5cfe4b517eb67124412285f2f1f394a1ac884e8

It requires that your login controller can redirect back to a URL afterwards (I don't think that is default laravel functionality?)

This package is assuming the laravel user is already authed which may not be the case.

**Comment by jimmypuckett** [comment]
We cannot replicate the issue.  We have Discourse configure to redirect an unthenicated user back to the Laravel site, which kicks in the auth middleware, so the user sees a login screen.  Upon login in, the user gets redirected to intended, so they go back to Discourse.

We are of the option that this is a difference in the configuration of Discourse, so we posted our configs.  If you can find a difference, then we can update the docs, but we cannot find anything to change/address.

We are not trying to ignore this request, we just cannot replicate it.

**Comment by robthompsonweb** [comment]
@jimmypuckett 
"We have Discourse configure to redirect an unthenicated user back to the Laravel site"
What setting is that in Discourse? I couldn't see that anywhere or in the config posted above

**Comment by jimmypuckett** [comment]
@robthompsonweb 

See: https://github.com/spinen/laravel-discourse-sso/issues/18#issuecomment-537993599 by @ssfinney about 5 post up.

**Comment by jimmypuckett** [comment]
@robthompsonweb, sorry, you are correct, those configs don't have that info.

**Comment by ssfinney** [comment]
@robthompsonweb The config that you'll need to set is "sso not approved URL", under Admin -> Login. Set that to your Laravel URL, and all unauthenticated users will be sent back to Laravel.

I'm sorry the picture above didn't have that in there; it got cut off for some reason.

**Comment by jimmypuckett** [comment]
@ssfinney Thanks for following up.  Is there something that we are missing in the docs?

**Comment by ssfinney** [comment]
@jimmypuckett Yeah, definitely. I'm going to re-open this issue so I can document.

**Comment by ssfinney** [comment]
@jimmypuckett I pushed the documentation straight to develop, sorry. Didn't make a feature.

But here is the documentation. I made it into two tables of the config items we set in Discourse. Thoughts?

![Screen Shot 2020-04-03 at 12 42 20 PM](https://user-images.githubusercontent.com/1596394/78384670-9a2fc980-75a8-11ea-8763-3775fca03e5b.png)

**Comment by jimmypuckett** [comment]
@ssfinney I think that this is great.  2 points...

1) Should these sections be with the `Configuration` section, where we make subsections?
2) should the ones with `Our Laravel homepage (FQDN)` be `Our Laravel homepage (same as "url" in "config/app.php")`

@robthompsonweb Will you please confirm that these settings help you?

**Comment by ssfinney** [comment]
@jimmypuckett OK, I've made those changes

**Comment by ssfinney** [comment]
Tagged these changes @ 2.5.0

**Comment by jimmypuckett** [comment]
@ssfinney I am closing this as 2.5.0 fixed.
