### ISSUE TITLE
Need help troubleshooting and determining correct setting values

### ISSUE THREAD

**Issue by nathan-io** [spinen/laravel-discourse-sso#26]
Hello,

I followed the instructions:

- `composer require spinen/laravel-discourse-sso`
- add array to `config/services.php`
- change settings in Discourse admin panel

I'm logged in to the Laravel application. However, when I visit the Discourse instance, I'm not logged in. If I click "Log In," I'm directed back to account.mydomain.com (with an `sso` URL parameter) which is the URL where I would log in to Laravel if unauthenticated.

I'm confused about two settings, which I think could be the issue:

- "sso url (Our Laravel's SSO route (FQDN))" - what is meant by "SSO route" here? Do I need to set up a route in the Laravel application where I installed this package, and if so, what should it run when hit? 
- "sso key" - is this just a key that I generate? The docs aren't clear what this key is or where it comes from. I generated a random string for this, and put it in Laravel's `.env` as well as the Discourse settings.

Thank you.

**Comment by nathan-io** [comment]
Sorry, figured it out just after posting.

I changed the SSO route in Discourse config to `https://account.mydomain.com/discourse/sso` and that got it working.

**Comment by jimmypuckett** [comment]
@nathan-io I am glad you worked it out.  I hope the package is helpful for you.
