### ISSUE TITLE
Composer issue on Laravel 8

### ISSUE THREAD

**Issue by nathan-io** [spinen/laravel-discourse-sso#36]
In `composer.json`, we're requiring `"guzzlehttp/guzzle": "^7.0.1"` per the Laravel 8 [dependency upgrade guide](https://laravel.com/docs/8.x/upgrade#updating-dependencies) and `"spinen/laravel-discourse-sso": "^2.5.2"`.

Result of `composer update`:

```
  Problem 1
    - Can only install one of: guzzlehttp/guzzle[7.0.1, 6.5.x-dev].
    - Can only install one of: guzzlehttp/guzzle[7.0.x-dev, 6.5.x-dev].
    - Can only install one of: guzzlehttp/guzzle[7.1.x-dev, 6.5.x-dev].
    - spinen/laravel-discourse-sso 2.5.2 requires guzzlehttp/guzzle ^6.4 -> satisfiable by guzzlehttp/guzzle[6.5.x-dev].    - Installation request for spinen/laravel-discourse-sso ^2.5.2 -> satisfiable by spinen/laravel-discourse-sso[2.5.2].
```

I think the package `composer.json` may need to be updated to support both `guzzle` 6.x and 7.x? Not entirely sure of the fix.

**Comment by jimmypuckett** [comment]
@nathan-io Thanks.  I am making a fix now.

tag @ssfinney

**Comment by jimmypuckett** [comment]
Just pushed 2.5.3, so let reopen if that does not fix your issue.

Thanks!

**Comment by nathan-io** [comment]
Thanks @jimmypuckett !

I updated `composer.json` to require ^2.5.3, am now I'm getting this:

```
  Problem 1
    - The requested package spinen/laravel-discourse-sso ^2.5.3 exists as spinen/laravel-discourse-sso[1.0.0, 1.0.1, 1.1.0, 1.1.1, 1.2.0, 1.3.0, 1.4.0, 1.5.0, 2.0.0, 2.1.0, 2.2.0, 2.2.1, 2.3.0, 2.4.0, 2.5.0, 2.5.1, 2.5.2, dev-develop, dev-feature/addLaravel5.8Support, dev-feature/allowNewerGuzzle, dev-feature/upgradeLaravel8, dev-master] but these are rejected by your constraint.
```

**Comment by nathan-io** [comment]
So I think that was some kind of hiccup with Packagist or something. I tried again a minute later, and didn't get that error (now Composer is complaining about a different package).

I think that solved it, thanks again.

**Comment by ssfinney** [comment]
@nathan-io Yeah, I'm thinking Packagist was just behind by a little bit. Let us know if something else comes up!
