### ISSUE TITLE
add_groups not working ?

### ISSUE THREAD

**Issue by mydnic** [spinen/laravel-discourse-sso#39]
Hello and thanks for this awesome package !

I use the latest version of laravel and discourse

My config is set like this :

```php
'add_groups' => 'discourse_groups'
```

I've add a `getDiscourseGroupsAttribute()` method on my user model and it seems to be working

Using tinker I confirm having these results

```
>>> User::find(22)->discourse_groups
=> "manager,parents"
>>> config('services.discourse.user.add_groups')
=> "discourse_groups"
>>> 
```

The Discourse SSO login works fine, but when I inspect the new user in discourse, I check the last payload under SSO informations and I see this:

`add_groups=manager%2Cparents`

I correctly have those two groups in my discourse
![Screenshot 2021-05-12 at 15 26 31](https://user-images.githubusercontent.com/2733767/117982728-98e9d800-b336-11eb-84a8-3c1a28f1cdc3.png)
![Screenshot 2021-05-12 at 15 27 02](https://user-images.githubusercontent.com/2733767/117982730-98e9d800-b336-11eb-96a2-a44316224f41.png)

But the user is not added to them
![Screenshot 2021-05-12 at 15 28 08](https://user-images.githubusercontent.com/2733767/117982831-b1f28900-b336-11eb-87f7-f2920f592975.png)

**Comment by mydnic** [comment]
I disabled "discourse connect overrides groups" and now it works

**Comment by ssfinney** [comment]
Thanks for the update! I'm glad it's working now.
