### ISSUE TITLE
How to test the laravel-discourse-sso on my local environment

### ISSUE THREAD

**Issue by chiefpunk** [spinen/laravel-discourse-sso#40]
Now our forum URL is https://community.claritycooperative.com/
And our app is working on http://localhost:3000
What is the discourse_url on the config?
And also the discouse_api_user?

Is this working in the local environment?

Currently, I put the discourse_url with http://localhost:300 on the config and http://localhost:3000/discourse/sso is also the discourse URL on the forum admin.
Then I enabled the discourse connect on the admin.
After that, whenever I click the login button it always redirects to the http://localhost:3000/discourse/sso?sso=bm9uY2U9Y2I2ODI1MWVlZmI1MjExZTU4YzAwZmYxMzk1ZjBjMGI%3D%0A&sig=2828aa29899722b35a2f191d34ef9b3ce695e0e6eeec47deb46d588d70c7cb56.

Please help me what is the issue now.
Thanks

**Comment by ssfinney** [comment]
Hi! Thanks for reaching out.

The discourse_url is the landing page of your Discourse forum; so it looks like you are correct with using http://localhost:3000.

The discourse_api_user is the name of the user holding the API key for the SSO Discourse integration. It might just be "admin" but there is a name in the Discourse admin panel.

When you click your login button, you are correctly getting a redirect to the SSO route. What happens after the redirect? Is there an error on the screen? What about in your console, is there an error there?
